name: check

on:
  pull_request:
    branches: 
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod download

      - name: Run all checks (fmt-check, vet, lint, test)
        run: make check
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod download

      - name: Build the project
        run: make build
